---
"parser": "babel-eslint"
"extends": "xo-space"
"env":
  "mocha": true
  "amd": true
  "browser": true
"rules":
  "comma-dangle":
    - 2
    - "always-multiline"
  "object-curly-spacing":
    - 2
    - "always"
  "linebreak-style": 0
  "curly":
    - 2
    - "multi-line"
  "arrow-parens": 0
  "babel/arrow-parens":
    - 2
    - "as-needed"
"plugins":
  - "babel"
